### ISSUE TITLE
Dark mode support for boxes

### ISSUE THREAD

**Issue by jpf91** [RoneoOrg/hugo-shortcode-roneo-collection#7]
Would it be possible to introduce dark mode support for the boxes? This works fine for me with the PaperMod theme:

```css
:root {
  --box-bg: #f3ebe850;
  --box-warning-bg: #ff6b6b4f;
  --box-important-bg: #f7ec2c7d;
  --box-info-bg: #0089e41c;
  --box-tip-bg: #a3ffa34d;
  --box-text: #444;
}

.dark {
  --box-bg: #f3ebe830;
  --box-warning-bg: #ff6b6b40;
  --box-important-bg: #f7ec2c30;
  --box-info-bg: #0089e430;
  --box-tip-bg: #a3ffa330;
  --box-text: var(--content);
}

.box-shortcode {
      padding: 1.6em;
      padding-top: 1.4em;
      line-height: 1.4em;
      margin-top: 1em;
      margin-bottom: 2em;
      border-radius: 4px;
      color: var(--box-text);
      background: var(--box-bg);
    }
    .box-shortcode.warning {
      background: var(--box-warning-bg);
    }
    .box-shortcode.info {
      background: var(--box-info-bg);
      box-shadow: 3px 3px 5px #0089e410;
    }
    .box-shortcode.important {
      background: var(--box-important-bg);
    }
    .box-shortcode.tip {
      background: var(--box-tip-bg);
      box-shadow: 3px 3px 5px #0089e410;
    }
```

Result:

![Image](https://github.com/user-attachments/assets/437307f7-f6f2-47d7-8e32-c10ace9a4a40)

Also something I noticed when editing the CSS: Ist he `.box-title` CSS ever used?
